### ISSUE TITLE
[建议] 添加vivaldi浏览器以及移除欧朋浏览器

### ISSUE THREAD

**Issue by yzqzss** [cjh0613/anti-selfish-browser#4]
## 建议

opera已被360收购，虽然大概率不会影响opera国际版的隐私和安全性，但万一呢？

Vivaldi是薇荻科技（Vivaldi Technologies）公司开发的网页浏览器。由创始人谭咏文（前Opera软件公司的首席执行官、创办人）与富田龙起（Tatsuki Tomita，前Opera软件公司资深副总经理）在离开Opera公司后另起炉灶新创办。  --( https://zh.wikipedia.org/wiki/Vivaldi_(%E7%80%8F%E8%A6%BD%E5%99%A8) )

---

**Comment by cjh0613** [comment]
收到，考虑中……

**Comment by cjh0613** [comment]
@yzqzss 您有兴趣协助 PR 修改一下吗？HTML 只需要修改 en 及 zh-Hans 即可

**Comment by cjh0613** [comment]
我已在代码中实现此建议。
